import { Navbar } from './Navbar/Navbar'
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>SIREN Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}  
    </div>
  )
}